import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/elements/theme-provider";
import Navbar from "@/components/elements/Nabar"
import { Toaster } from "@/components/ui/toaster"
import { SessionProvider } from "next-auth/react";
import Footer from "@/components/elements/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className="dark">
      <body className="font-sans flex flex-col min-h-screen ">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SessionProvider>
            <Navbar/>
            <div className="container mx-auto border-md shadow-lg border-gray-200
                          lg:min-h-[760px] 
                            overflow-hidden rounded-lg p-3  ">
              {children}
            </div>
              <Footer/>
            <Toaster/>
            </SessionProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
